version: "3.8"

services:
  master-node:
    image: "babylonchain/babylond"
    container_name: master-node
    command: tail -f /dev/null  # This keeps the container running
    volumes:
      - ./scripts:/scripts:ro
      - ./snapshots:/snapshots:ro
    ports:
      - "26656:26656"    # Tendermint RPC
      - "26657:26657"    # Tendermint P2P
      - "1317:1317"      # REST API
      - "9090:9090"      # gRPC
      - "2345:2345"      # Debugging
    networks:
      - babylon-net

  follower-node:
    image: "babylonchain/babylond"
    container_name: follower-node
    command: >
      babylond start --home /babylondhome --log_format 'plain'
    volumes:
      - ./data/follower:/babylondhome
    ports:
      - "26658:26656"    # Tendermint RPC for follower
      - "26667:26657"    # Tendermint P2P for follower
      - "1318:1317"      # REST API for follower
      - "9091:9090"      # gRPC for follower
      - "2346:2345"      # Debugging for follower
    networks:
      - babylon-net
    depends_on:
      - master-node

networks:
  babylon-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  babylondhome: