name: ci

on:
  pull_request:
    branches:
    - '**'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.11.2
    with:
     go-version: '1.23'
     go-lint-version: 'v1.60.2'
     run-unit-tests: false
     run-integration-tests: true
     run-lint: true
     install-dependencies-command: |
       sudo apt-get update
       sudo apt-get install -y libzmq3-dev
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download
      
    - name: Run tests
      run: go test ./... -v


